Hack4Impact-UMD/food-for-all-dc

my-app/src/components/Calendar/CalendarPage.css
my-app/src/components/Calendar/CalendarPage.tsx

used placeholder values for everything but the client name in the new day view, since the clients and events databases are not connected yet. i also carried forth the arrow design from the new day view to the other views

implemented new Day view design

---

my-app/src/components/Calendar/CalendarPage.tsx

- fixed event layout (looks presentable now)
- added "priority" as a field to new delivery creation and popup
- added scroll box to present dietary restrictions 
- linked client fields in events to client firebase
- added button to bring user to "today's" events
- made the view-changing button visible (since the new navbar was hiding it)
- clicking "notes and details" now takes user to the spreadsheet page

(dramatically) improved layout and functionality of calendar

---

my-app/src/pages/Login/Login.tsx

Removed the "Are you a volunter" <p> tag and I blurred the password.

Login page blur

---

my-app/src/pages/Profile/Profile.tsx

Changed:
Language --> Textfield to dropdown, if other is selected, lets user input a custom language with text field
Ethnicity --> Textfield to dropdown, filled with placeholders for now
Phone Number --> Updated regex to support (XXX-XXX-XXXX), updated error message to account for that, renamed text field headers to those specified in notion
Delivery Frequency --> Textfield to dropdown, options match those specified in notion

Profile page dropdowns

---

my-app/src/components/Calendar/CalendarPage.tsx
my-app/src/components/Calendar/CalendarPopper.tsx

Removed logging statements left over from development

removed console.log statements from calendar page and popper components

---

my-app/src/pages/Delivery/DeliverySpreadsheet.tsx

- Added a clusterID field to the existing users for their assigned cluster (did not change the create client though)
- Added a clusters collection and drivers collection based on the interfaces in the Notion (defaulted to 5 clusters for now)
- Clients with the cluster are linked together. Selecting a user will select all other users with the same cluster.
- Assigning a driver/time will modify the cluster in the db with the updated information.

Delivery route page client spreadsheet view

---

my-app/src/pages/Base/Base.tsx

Current page title is now displayed in the navbar for each page

Added page header to navbar

---

my-app/src/components/Spreadsheet/Spreadsheet.tsx

- Added custom column functionality letting user add more columns to view client data
- Added ability to delete custom columns after adding
- Integrated custom columns with existing search logic
- Did some styling

Custom filtering

---

my-app/src/components/Calendar/CalendarPage.tsx
my-app/src/components/Calendar/CalendarPopper.tsx
my-app/src/components/Calendar/CalendarUtils.ts
my-app/src/components/Calendar/useLimits.ts

- Added a custom Hook to get day of the week limits from FB
- Let user bulk edit limits for days of the week (editable via a toggle feature)
- Stored limits globally in FB

Calendar standardization

---

my-app/src/pages/Delivery/DeliverySpreadsheet.tsx
package-lock.json

Export CSV frontend and adding columns "Phone Number" and "Notes"

---

my-app/firebase.json
my-app/functions-python/clustering.py
my-app/functions-python/main.py
my-app/functions-python/requirements.txt
my-app/functions/src/index.ts
my-app/package-lock.json
my-app/package.json
my-app/src/pages/Delivery/ClusterMap.tsx
my-app/src/pages/Delivery/DeliverySpreadsheet.tsx

should be a working version but still in progress to clean up code and write documentation

Evan clustering work in progress

---

my-app/src/pages/Profile/Profile.tsx

Added TEFAP certification field to Profile page

New profile page fields

---

my-app/src/components/Spreadsheet/Spreadsheet.tsx
my-app/src/hooks/useCustomColumns.ts
my-app/src/pages/Delivery/DeliverySpreadsheet.tsx

Features added:
Custom Columns feature
Hooks folder to separate out custom columns logic. 
Minor edits to the styles of the rows.

Add custom/dynamic columns to Route page.

---

my-app/src/App.tsx
my-app/src/pages/Base/Base.tsx

As stated in the title, I reordered the navbar so that `Clients` is the first page and icon.

Reordered navbar

---

my-app/src/pages/Profile/Profile.css
my-app/src/pages/Profile/Profile.tsx

To fix the cancel button not exiting edit mode, I removed the `setIsEditing(false)` line from the `handleCancel` function. To fix the cancel button not being centered, I made a new css class to ensure it stays centered.

Fixed the issues revolving the cancel button not exiting edit mode and the cancel button not being centered.

---

my-app/src/pages/Profile/Profile.tsx

The issue was that `setIsEditing(false)` was added as the last line in the `handleCancel` function which caused the issue of editing mode not closing when pressing the cancel button. I removed this line and now the cancel button works as intended.

Fix the bug where clicking the cancel button in edit mode does not close editing mode.

---

my-app/src/components/Spreadsheet/Spreadsheet.css
my-app/src/components/Spreadsheet/Spreadsheet.tsx
my-app/src/pages/Profile/Profile.tsx

Added a tag to the client's names to navigate to that client's profile page. Let me know if the styles are good or if I should change them to something else.

Client name hyperlink

---

my-app/src/components/Spreadsheet/Spreadsheet.css
my-app/src/components/Spreadsheet/Spreadsheet.tsx
my-app/src/pages/Profile/Profile.tsx

To fix it I added a special case in the `else` block of the `handleChange` function. The `name` field from the event comes in as "deliveryDetails.deliveryInstructions", which requires us to carefully handle the nested property.

Delivery instruction edit fix

---

my-app/src/components/Calendar/CalendarPage.tsx
my-app/src/components/Calendar/CalendarPopper.tsx
my-app/src/components/Calendar/CalendarUtils.ts
my-app/src/components/Spreadsheet/Spreadsheet.css
my-app/src/components/Spreadsheet/Spreadsheet.tsx
my-app/src/pages/Profile/Profile.tsx

Fixes for various bugs on the deliveries page. This includes:
1. The bug in calendar view where days of months other than the current one being viewed were not showing how many deliveries they have.
2. The edit limits modal goes away when you click anywhere outside of it.
3. The recurrence label in the add deliveries form is now properly outlined.

Delivery Page fixes

---

my-app/src/components/Spreadsheet/Spreadsheet.tsx
my-app/src/pages/Delivery/DeliverySpreadsheet.tsx

Updated search method in routes and spreadsheet to also use quote search (Google)

Quote search

---

my-app/src/pages/Base/NavBar/Tab.css
my-app/src/pages/Base/NavBar/Tab.tsx

The navbar elements would not make the mouse go into pointer mode, so I adjusted the CSS styles for the Tab components. There were also in JS errors where the "==" sign was being used over the "===" sign.

Add cursor point to Tab styles css, make == into === for JS conventions.

---

my-app/src/pages/Profile/Profile.tsx

Basically added the lines necessary in the handleTag function.

Fix bug for tags not resetting when user cancels their edits.

---

my-app/src/components/Spreadsheet/Spreadsheet.tsx
my-app/src/pages/Profile/Profile.tsx
my-app/src/pages/Profile/Tags/Tag.tsx
my-app/src/pages/Profile/Tags/TagPopup.tsx
my-app/src/pages/Profile/Tags/Tags.tsx

- Changed client profile page to display tags at the top, and be editable via clicking to remove tag from user
- Rightmost tag is an edit tag that opens a modal letting the user add tags to the user (and add new tags as a whole)
- User can remove tags (as a whole) by toggling to the remove mode.

Tags update

---

my-app/package-lock.json
my-app/package.json
my-app/src/pages/Profile/Profile.tsx
my-app/src/pages/Profile/components/BasicInfoForm.tsx

For the bug fix, changed behavior of validateProfile to now return an object. Also added a check for emails for errors which was missing.

Made referral an autocomplete field, fixed bug, added checking for email in errors

---

my-app/src/hooks/useCustomColumns.ts
my-app/src/pages/Delivery/DeliverySpreadsheet.tsx

Added custom column functionality to delivery page
Updated existing search logic to account for custom columns
- Also updated it to account for already existing columns (only used name before)
Kept styling to be same as client custom columns

Custom columns delivery

---

my-app/src/components/Spreadsheet/DeleteClientModal.tsx
my-app/src/components/Spreadsheet/Spreadsheet.tsx
my-app/src/pages/Base/Base.tsx

- dialog now has translucent backdrop instead of opaque black

Client delete confirmation

---

my-app/src/pages/Delivery/DeliverySpreadsheet.tsx
my-app/src/pages/Delivery/components/ClientCard.tsx
my-app/src/pages/Delivery/components/ManualAssignPopup.tsx
my-app/src/pages/Delivery/types/deliveryTypes.ts
my-app/src/pages/Profile/Profile.tsx
my-app/src/types/client-types.ts

Added new function getCoordinates to Profile page that gets the coordinates and stores in firebase upon saving the profile. Switched to this method instead of geocoding in delivery page.

added coordinate caching on profile save

---

my-app/src/pages/Delivery/DeliverySpreadsheet.tsx

I fixed the assigned time on the delivery page and made it much cleaner.

fixed the assign time on the delivery page

---

my-app/src/pages/Profile/Profile.tsx
my-app/src/pages/Profile/components/BasicInfoForm.tsx

added dropdowns to profile page fields when in edit mode

Profile field dropdowns

---

my-app/src/config/exportConfig.ts
my-app/src/pages/Delivery/RouteExport.tsx

- Updated format to follow Graeme's specifications for the DoorDash download export

Updating doordash export format
